config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :adventures

  root 'welcome#index'

end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
	 validates :animal, presence: true, length: { minimum: 3 }
	 validates :amount, presence: true
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
	
	def new
		@adventure = Adventure.new
  	end

  	def index
  		@adventure = Adventure.all
  	end

  	def show
  		@adventure = Adventure.find(params[:id])
  	end

  	def create
  		@adventure = Adventure.new(adventure_params)
 
  		if @adventure.save
  			redirect_to @adventure
  		else
  			render 'new'
  		end
  	end

  	private
  		def adventure_params
  			params.require(:adventure).permit(:animal, :amount)
  		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/adventures/index.html.erb
<h1>Listing Animals</h1>
 
<h2>Monday 2nd Feb</h2>

<table>
  <tr>
    <th>Animal</th>
    <th>Amount</th>
  </tr>
 
  <% @adventure.each do |adventure| %>
    <tr>
      <td><%= adventure.animal %></td>
      <td><%= adventure.amount %></td>
    </tr>
  <% end %>
  
</table>

<%= link_to 'New Adventure', new_adventure_path %>

app/views/adventures/new.html.erb
<h1>New Adventure</h1>

 <% if @adventure.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@adventure.errors.count, "error") %> prohibited
        this adventure from being saved:
      </h2>
      <ul>
        <% @adventure.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for :adventure, url: adventures_path do |f| %>
  <p>
    <%= f.label :animal %><br>
    <%= f.text_field :animal %>
  </p>
 
  <p>
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', adventures_path %>

app/views/adventures/show.html.erb
<p>
  <strong>My Animal:</strong>
  <%= @adventure.animal %>
</p>
 
<p>
  <strong>How Many:</strong>
  <%= @adventure.amount %>
</p>

<%= link_to 'Back', adventures_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Ranger!</h1>
<%= link_to 'New Adventure', new_adventure_path %>
<%= link_to 'Adventures', controller: 'adventures' %>